version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: cruddb  # This will create the 'userdb' database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./user-service/userschema.sql:/docker-entrypoint-initdb.d/userdb.sql
      - ./product-service/productschema.sql:/docker-entrypoint-initdb.d/productdb.sql
      - ./order-service/orderschema.sql:/docker-entrypoint-initdb.d/orderdb.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=userdb # This needs to be the database for the server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  product-service:
    build: ./product-service
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=productdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  order-service:
    build: ./order-service
    depends_on:
      - postgres
    ports:
      - "8083:8083"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:


